name: MyBuild

on:
  push:
    branches: 
     - main
     - 'feature/**'
     - 'dev/**'
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'information'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore ./WebAPI/VeggiFoodAPI/VeggiFoodAPI.csproj
    - name: Build
      run: dotnet build ./WebAPI/VeggiFoodAPI/VeggiFoodAPI.csproj --configuration Release --no-restore
  PublishArtifacts:
    needs: Build
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Show default environment variables
      run: |
        echo "The version is: $PACKAGE_VERSION"
        echo "The version is: $PACKAGE_VERSION.rc"
