name: Build, Dockerize, and Deploy

on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Replace with the desired .NET Core version

    - name: Restore NuGet packages
      run: dotnet restore ./WebAPI/VeggiFoodAPI/VeggiFoodAPI.csproj

    - name: Build
      run: dotnet build ./WebAPI/VeggiFoodAPI/VeggiFoodAPI.csproj --configuration Release

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: https://registry.hub.docker.com/v2/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t dsmercy:${{ github.sha }} ./WebAPI/VeggiFoodAPI/Dockerfile .
        docker push dsmercy:${{ github.sha }}

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Octopus
      uses: OctopusDeploy/action-create-release@v1
      with:
        OctopusServerEndpoint: '<octopus-server-url>'
        OctopusApiKey: ${{ secrets.OCTOPUS_API_KEY }}
        SpaceName: '<octopus-space-name>'
        ProjectName: '<octopus-project-name>'
        PackageVersion: '${{ github.sha }}'
        ReleaseVersion: '${{ github.sha }}'
        AdditionalArguments: '--packageversion=$RELEASE_VERSION'
